apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output
  namespace: shinyproxy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 50Gi