apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: shinyproxy
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 50Gi