apiVersion: openanalytics.eu/v1
kind: ShinyProxy
metadata:
  name: shinyproxy
  namespace: shinyproxy
spec:
  logging:
    requestdump: true
    level:
      DEBUG
  server:
    secureCookies: true
    frameOptions: sameorigin
    forward-headers-strategy: native
    servlet.session.timeout: 3600
  spring:
    session:
      store-type: redis
    data:
      redis:
        password: ${REDIS_PASSWORD}
        sentinel:
          master: shinyproxy
          password: ${REDIS_PASSWORD}
          nodes: redis-node-0.redis-headless:26379, redis-node-1.redis-headless:26379, redis-node-2.redis-headless:26379
  proxy:
    store-mode: Redis
    stop-proxies-on-shutdown: false
    title: ShinyProxy
    logoUrl: ""
    landingPage: /
    containerBackend: kubernetes
    kubernetes:
      namespace: shinyproxy
      internal-networking: true
      image-pull-policy: Always
    authentication: none
    admin-groups: scientists
    my-apps-mode: Inline
    users:
      - name: jack
        password: password
        groups: scientists
      - name: jeff
        password: password
        groups: mathematicians
    specs:
      - id: 01_hello
        display-name: Hello Application
        description: Application which demonstrates the basics of a Shiny app
        container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
        container-image: openanalytics/shinyproxy-demo
        access-groups: [scientists, mathematicians]
      - id: 06_tabsets
        container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
        container-image: openanalytics/shinyproxy-demo
        access-groups: scientists
      - id: rstudio
        displayName: RStudio
        description: RStudio
        containerImage: openanalytics/shinyproxy-rstudio-ide-demo:1.4.1106__4.0.4
        port: 8787
        container-env:
          DISABLE_AUTH: true
          WWW_ROOT_PATH: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"
  kubernetesPodTemplateSpecPatches: |
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis
            key: redis-password
    - op: add
      path: /spec/containers/0/resources
      value:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 0.5
          memory: 1Gi
    - op: add
      path: /spec/serviceAccountName
      value: shinyproxy-sa
  kubernetesServicePatches: |
    - op: add
      path: /metadata/annotations
      value:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    - op: replace
      path: /spec/type
      value: LoadBalancer
  image: openanalytics/shinyproxy:3.1.1
  imagePullPolicy: Always
  fqdn: shinyproxy-demo.local