
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis
    includeCRDs: false
    valuesInline:
      global:
        redis:
          password: abc
      sentinel:
        enabled: true
        masterSet: shinyproxy
    releaseName: redis
    version: 17.3.14
    repo: https://charts.bitnami.com/bitnami
    namespace: replace_this_namespace

patchesJSON6902:
  - target:
      name: ".*"
    patch: |-
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1managed-by
      - op: remove
        path: /metadata/labels/helm.sh~1chart
      - op: remove
        path: /metadata/namespace
